
spring:
  profiles:
    active:
      - dev

---

server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huashang
    username: root
    password: root
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
mybatis-plus:
  mapper-locations: classpath:cn/xf/huashang/mapper/*Mapper.xml
  type-aliases-package: cn.xf.huashang.pojo

---

server:
  port: 8022
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huashang
    username: root
    password: root
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
mybatis-plus:
  mapper-locations: classpath:cn/xf/huashang/mapper/*Mapper.xml
  type-aliases-package: cn.xf.huashang.pojo