spring:
  profiles:
    active:
      - dev

---

server:
  port: 9527
spring:
  application:
    name: HUASHANG-ZUUL-GATEWAY
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
    instance-id: gateway-9527
zuul:
  prefix: "/huashang"
  ignored-services: "*"
  routes:
    product.serviceId: product-service
    product.path: /product/**
    plat.serviceId: plat-service
    plat.path: /plat/**

---

server:
  port: 9528
spring:
  application:
    name: HUASHANG-ZUUL-GATEWAY
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
    instance-id: gateway-9527
zuul:
  prefix: "/huashang"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**
    product.serviceId: product-service
    product.path: /product/**

0.
00//85