spring:
  profiles:
    active:
      - dev

---

server:
  port: 9527
spring:
  application:
    name: HUASHANG-ZUUL-GATEWAY
    profile: dev
zuul:
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**  #路由映射：/wbUser/**这个路径的访问都路由到serverId服务处理
  ignored-services: "*" # 安全加固：忽略这个服务，如果要忽略所有的服务， “*”
  prefix: "/huashang"  # 统一前缀

---

server:
  port: 9528
spring:
  application:
    name: HUASHANG-ZUUL-GATEWAY
    profile: test
zuul:
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**  #路由映射：/wbUser/**这个路径的访问都路由到serverId服务处理
  ignored-services: "*" # 安全加固：忽略这个服务，如果要忽略所有的服务， “*”
  prefix: "/huashang"  # 统一前缀
